WITH ABC AS
(
  SELECT
  *
  FROM
  (
    Select
    A.YEARMONTH, A.ZKEY, A.DOM_TYPE_II, A.DIVISION_NAME, A.CREDIT_BIN, A.OS_HA, A.EVER_S2S_CUST, a.ACCOUNT_NAME,
    A.EVER_FOL_CUST, A.EVER_EBIZ_CUST, A.MON, A.FRIENDLY,
    CASE WHEN A.FIRST_S2S_ORDER <= A.YEARMONTH THEN 1 ELSE 0 END S2S_CURRENT_CUST,
    CASE WHEN A.FIRST_FOL_ORDER <= A.YEARMONTH THEN 1 ELSE 0 END FOL_CURRENT_CUST,
    CASE WHEN A.FIRST_EBIZ_ORDER <= A.YEARMONTH THEN 1 ELSE 0 END EBIZ_CURRENT_CUST,
    A.FIRST_FEI_ORDER, A.FIRST_S2S_ORDER, A.CUST_SLS_TM, A.CUST_JOB_SLS,
    A.CUST_SLS_12M, A.CNT_ROLLING_MONTHS,A.BRANCH_SLS_12M,A.BRANCH_SLS_TM,A.CNT_YM,
    ROW_NUMBER() OVER(PARTITION BY A.ZKEY ORDER BY A.YEARMONTH ASC) AS TREND
    
    
    from NORTH.X_TEMPYTEMPY A
    
    WHERE A.CUST_SLS_TM >= 1
    AND A.BRANCH_SLS_TM >= 1
  ) B
  WHERE B.TREND > 5
)

SELECT
AA.*,Z.RAND
FROM
(
  SELECT X.ZKEY, dbms_random.value as RAND FROM (SELECT DISTINCT ABC.ZKEY FROM ABC) X
) Z
JOIN
(
  SELECT * FROM ABC
) AA
ON Z.ZKEY = AA.ZKEY
WHERE Z.RAND <= .25