  SELECT
  *
  FROM
  (
    Select
    A.YEARMONTH, A.ZKEY, A.DOM_TYPE_II, A.DIVISION_NAME, A.CREDIT_BIN, A.OS_HA, A.EVER_S2S_CUST, a.ACCOUNT_NAME,
    A.EVER_FOL_CUST, 
    CASE WHEN A.EVER_S2S_CUST + A.EVER_FOL_CUST > 0 THEN 1 ELSE 0 END AS EVER_EBIZ_CUST, 
    A.MON, A.FRIENDLY,
    CASE WHEN A.FIRST_S2S_ORDER <= A.YEARMONTH THEN 1 ELSE 0 END S2S_CURRENT_CUST,
    CASE WHEN A.FIRST_FOL_ORDER <= A.YEARMONTH THEN 1 ELSE 0 END FOL_CURRENT_CUST,
    CASE WHEN A.FIRST_EBIZ_ORDER <= A.YEARMONTH THEN 1 ELSE 0 END EBIZ_CURRENT_CUST,
    A.FIRST_FEI_ORDER, A.FIRST_S2S_ORDER, A.CUST_SLS_TM, 
    A.CUST_SLS_TM - CUST_COGS_TM AS CUST_GP_TM,
    A.CUST_JOB_SLS, A.CNT_ROLLING_MONTHS,A.BRANCH_SLS_TM,
    A.BRANCH_SLS_TM - A.BRANCH_COGS_TM AS BRANCH_GP_TM,
    A.CNT_YM,
    ROW_NUMBER() OVER(PARTITION BY A.ZKEY ORDER BY A.YEARMONTH ASC) AS TREND
    
    
    from
    (
      Select bch.YEARMONTH, FC.ZKEY, FC.DOM_TYPE_II, FC.DIVISION_NAME, BCH.ACCOUNT_NAME,
      CASE 
      WHEN TO_NUMBER(FC.CREDIT_LIMIT) < 2000 THEN 'LESS THAN 2K'
      WHEN TO_NUMBER(FC.CREDIT_LIMIT) < 15000 THEN '2K TO 15K'
      WHEN TO_NUMBER(FC.CREDIT_LIMIT) < 75000 THEN '15K TO 75K'
      ELSE 'OVER 75K'
      END CREDIT_BIN, FC.OS_HA, 
      
      CASE WHEN MAX(MAX(TO_NUMBER(NVL(bch.FIRST_S2S_ORDER,'0')))) OVER(PARTITION BY FC.ZKEY) = 0 THEN 0 ELSE 1 END EVER_S2S_CUST,
      CASE WHEN MAX(MAX(TO_NUMBER(NVL(BCH.FIRST_ORDER,'0')))) OVER(PARTITION BY FC.ZKEY) = 0 THEN 0 ELSE 1 END EVER_FOL_CUST,
      SUM(COUNT(DISTINCT BCH.YEARMONTH)) OVER(PARTITION BY FC.ZKEY) CNT_YM,
      
      BCH.MON, FC.FRIENDLY, 
      MIN(MIN(CASE WHEN BCH.TOTAL_ORDERS  > 0 THEN TO_NUMBER(BCH.YEARMONTH) else 999999 end)) over(partition by FC.ZKEY) FIRST_FEI_ORDER,
      min(min(TO_NUMBER(NVL(bch.FIRST_S2S_ORDER,'999999')))) over(partition by FC.ZKEY) FIRST_S2S_ORDER,
      min(min(TO_NUMBER(NVL(BCH.FIRST_ORDER,'999999')))) over(partition by FC.ZKEY) FIRST_FOL_ORDER,
      min(min(TO_NUMBER(
        CASE WHEN NVL(BCH.FIRST_ORDER,'999999') = '999999' AND NVL(bch.FIRST_S2S_ORDER,'999999') = '999999' THEN '999999'
        WHEN NVL(BCH.FIRST_ORDER,'999999') > NVL(bch.FIRST_S2S_ORDER,'999999') THEN NVL(bch.FIRST_S2S_ORDER,'999999') 
        ELSE NVL(BCH.FIRST_ORDER,'999999') end
      ))) over(partition by FC.ZKEY) FIRST_EBIZ_ORDER,
      sum(NVL(bch.NET_SALES,0)) CUST_SLS_TM,
      sum(NVL(bch.ALL_COGS,0)) CUST_COGS_TM,
      SUM(NVL(BCH.NET_JOB_SALES,0)) CUST_JOB_SLS,
      SUM(COUNT(DISTINCT CASE WHEN NVL(BCH.TOTAL_ORDERS,0) > 0 THEN BCH.YEARMONTH END)) OVER(PARTITION BY FC.ZKEY ORDER BY to_date(BCH.YEARMONTH || '01', 'yyyymmdd') RANGE BETWEEN INTERVAL '100' MONTH PRECEDING AND INTERVAL '0' MONTH PRECEDING) AS CNT_ROLLING_MONTHS,
      SUM(SUM(NVL(BCH.NET_SALES,0))) OVER(PARTITION BY BCH.ACCOUNT_NAME, bch.YEARMONTH) AS BRANCH_SLS_TM,
      SUM(SUM(NVL(bch.ALL_COGS,0))) OVER(PARTITION BY BCH.ACCOUNT_NAME, bch.YEARMONTH) AS BRANCH_COGS_TM
    
      
      from NORTH.BRANCH_CUSTOMER_HISTORY bch
      JOIN (
              SELECT FC123.ACCOUNT_NAME||FC123.MAIN_CUSTOMER_NK ZKEY, MAX(fc123.DOM_TYPE_II) DOM_TYPE_II, MAX(FC123.DIVISION_NAME) DIVISION_NAME, MAX(NVL(fc123.CREDIT_LIMIT,0)) CREDIT_LIMIT, MAX(FC123.OS_HA) OS_HA, MAX(FC123.PRICE_COLUMN) PRICE_COLUMN, MAX(FC123.FRIENDLY_PROFILE) FRIENDLY 
              FROM NORTH.FERGUSON_CUSTOMERS FC123
              JOIN AAI8260.MATCHED_ZKEYS_EBIZ@DWFEI MZK ON MZK.ZKEY = FC123.ACCOUNT_NAME||FC123.MAIN_CUSTOMER_NK
              WHERE FC123.CUSTOMER_TYPE not in ('0_BUYING_GROUP', 'CASH', 'E_EMPLOY', 'E_ENDUSER', 'E_ETAILER', 'EMPLOYEE', 'EXPORT', 'GOVT_AGENT', 'GOVT_STATE_EDUC', 'I_MISCELL', 'INDELECTRONIC', 'INDEQUIP', 'INDMISC', 'INDTRANSPOR', 'N_OEMFABDOM', 'N_OEMFABEXP', 'N_OEMMACDOM', 'N_OEMMACEXP', 'O_EXPORTER', 'O_FARM', 'O_OTHER', 'OTHER', 'T_CHURCH', 'U_REFUSE', 'UNKNOWN')
              GROUP BY FC123.ACCOUNT_NAME||FC123.MAIN_CUSTOMER_NK
            ) FC ON FC.ZKEY = BCH.ACCOUNT_NAME||BCH.MAIN_CUSTOMER_NK
      
      WHERE NVL(bch.NET_SALES,0) >= 1
      and NVL(bch.ALL_COGS,0) >= 1
      and NVL(bch.NET_SALES,0) > NVL(bch.ALL_COGS,0)
      
      group by
      bch.YEARMONTH, FC.ZKEY, FC.DOM_TYPE_II, FC.DIVISION_NAME, BCH.ACCOUNT_NAME,
      CASE 
      WHEN TO_NUMBER(FC.CREDIT_LIMIT) < 2000 THEN 'LESS THAN 2K'
      WHEN TO_NUMBER(FC.CREDIT_LIMIT) < 15000 THEN '2K TO 15K'
      WHEN TO_NUMBER(FC.CREDIT_LIMIT) < 75000 THEN '15K TO 75K'
      ELSE 'OVER 75K'
      END, FC.OS_HA, BCH.MON,FC.FRIENDLY, BCH.ACCOUNT_NAME
    ) A
    
    WHERE A.CUST_SLS_TM >= 1
    AND A.BRANCH_SLS_TM >= 1
  ) B
  WHERE B.TREND > 5

